version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/web_app
    steps:
      - checkout
      
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  
      - run: CI=true yarn test --silent --runInBand